apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-helm-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/isnt/play-with-argo-cd.git
    targetRevision: main
    path: charts/deploy-me-with-argo-cd
    helm:
      valueFiles:
        - /helm-values/production/example-application.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
